### ISSUE TITLE
为什么用fetch来代替axios作为http请求呢？

### ISSUE THREAD

**Issue by callmesoul** [pohunchn/vite-ts-quick#1]
为什么用fetch来代替axios作为http请求呢？
大部分都习惯了用axios啊，感觉用axios的话会比较顺手。
为啥要用fetch呢？有什么优势么？而且有些旧浏览器好像大支持fetch吧

**Comment by orziz** [comment]
就如同我这里自己写了一个 `Cookie` 而不是引用 `js-cookie` 一样，我承认已有的组件会更好的上手以及符合习惯，但是我认为就因为这一个单一需求而引入一个依赖并不是好的解决方案，更何况 `axios` 配置起来也不算特别简单。（虽然我封装的 `Fetch` 也是如此）。
`vite` 本身对浏览器就有一定的要求，我认为 `fetch` 所谓的兼容性其实问题并不大。`fetch` 比 `axios` 更轻，而且也是未来的新标准，为什么不尝试一下呢？
当然，如果您仍然习惯 `axios` ，那么可以自行配置，只是我个人不太建议。
