### ISSUE TITLE
是否应该在post的拦截器中再添加一个判断条件

### ISSUE THREAD

**Issue by FangDingli** [pohunchn/vite-ts-quick#2]
post请求时，如果请求头的Content-Type为 application/json ，是否应该对请求参数进行 JSON.stringify，否则在请求时payload依然为[object Object]

![image](https://user-images.githubusercontent.com/45346648/124732170-8f02e080-df45-11eb-8f24-7561f8f20a6c.png)

**Comment by orziz** [comment]
我认为，post请求的话，其实也不应该使用 "application/json"。这一块我其实没太想清楚，之前有专门针对这一块加了一个拦截器，你看代码应该能看出来，我写了一半注释掉了。
