### ISSUE TITLE
示例报错: [@vue/compiler-sfc] ref: sugar now needs to be explicitly enabled

### ISSUE THREAD

**Issue by lzhiming** [pohunchn/vite-ts-quick#3]
应该怎么配置啊
![image](https://user-images.githubusercontent.com/40237873/125020121-d951a200-e0aa-11eb-83c2-33d31eadabe1.png)

**Comment by lzhiming** [comment]
搞好了
script: {
      refSugar: true
    }

**Comment by orziz** [comment]
这个问题倒是没遇到过
