### ISSUE TITLE
Vuex HMR not working

### ISSUE THREAD

**Issue by ubzor** [pohunchn/vite-ts-quick#4]
Greetings! I'm trying to setup HMR for Vite + Vuex, found this project, but it seems that HMR is not working for modules in store here, though it is perfectly working for components. 

Steps to reproduce:
- git clone project
- yarn
- yarn dev
- open dev server url in browser
- change something in `src/store/modules/user.ts` and save changes
- notice full page reload instead of hmr update

Will be glad of any help in this matter, thank you!

**Comment by orziz** [comment]
I think this problem is due to the use of TS.
When change `.ts`, Vite used `esbuild` instead of HMR.

**Comment by ubzor** [comment]
I changed all TS files to be JS files and you are right, HMR in store started to work. So, you think currently there is no way to achieve my goal? HMR is working somehow for TS scripts in components. Anyway, thank you for your help.

**Comment by orziz** [comment]
yep, the problem of VITE and TS, and there is no good solution at present.
