### ISSUE TITLE
"vue-i18n": "^9.2.0-beta.11", There is a problem with this version dependency 

### ISSUE THREAD

**Issue by mtrucc** [pohunchn/vite-ts-quick#5]
https://github.com/pohunchn/vite-ts-quick/blob/27a52d57edddb4db86ff06ba4ca2401e32cf1ede/package.json#L12

![HGQ$G2VI1I2OQKUZ@)NPU~0](https://user-images.githubusercontent.com/16724665/137443256-f858755e-da5c-430e-a01b-4528f055f281.png)

please use
···
"vue-i18n": "^9.1.9"
···

**Comment by mtrucc** [comment]
Please follow https://github.com/intlify/vue-i18n-next/issues/746

**Comment by orziz** [comment]
fixed
