### ISSUE TITLE
could not find commit hash for HEAD

### ISSUE THREAD

**Issue by mzyaimll** [pohunchn/vite-ts-quick#6]
I try to running:
`npx degit pohunchn/vite-ts-quick web`
gives me:
`
! could not fetch remote https://github.com/pohunchn/vite-ts-quick
! could not find commit hash for HEAD
`
I checked  system enivroment path and update git latest.
It's not used.

**Comment by orziz** [comment]
you can try use `npx degit pohunchn/vite-ts-quick my-project` or `npx degit pohunchn/vite-ts-quick#main my-project`. also, I think you need check your network when you got `could not find commit hash for HEAD` or ` could not download`.
