### ISSUE TITLE
修改path=’/‘为自己写的页面组件时，build之后会报错

### ISSUE THREAD

**Issue by frankye23** [pohunchn/vite-ts-quick#7]
<img width="311" alt="ceafbed3a21a330a4507fbd8edcb8a3" src="https://user-images.githubusercontent.com/92201847/154442454-42a82123-e88a-4555-a9cd-603c147bd519.png">
<img width="778" alt="1bd24011baa921f736a46e1469a03c8" src="https://user-images.githubusercontent.com/92201847/154442530-4f129aca-de07-418b-8105-21fe2b739399.png">

**Comment by orziz** [comment]
![image](https://user-images.githubusercontent.com/36832622/155250918-58645815-d48a-48c3-b0e9-2e21b3388a2b.png)
亲，请在画红框的部分改
